name: Publish to GitHub Pages

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Init Repo
      run: npm init -y
    - name: Install Asciidoctor and reveal.js plugin
      run: npm i --save asciidoctor @asciidoctor/reveal.js
    - name: Generate docs-as-code Slides
      run: npx asciidoctor-revealjs ./src/docs/asciidoc/docs-as-code/docs_as_code.adoc -D ./build/slides/ -b revealjs
    - name: Generate docs-as-code Slides
      run: node ./convert-slides.js
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/slides